"""Adiciona jogo_finalizado em jogos e cartões em jogadores

Revision ID: 20bef6b5cc5d
Revises: 4a52526ea357
Create Date: 2025-03-12 10:00:29.119473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bef6b5cc5d'
down_revision: Union[str, None] = '4a52526ea357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jogos', sa.Column('jogo_finalizado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jogos', 'jogo_finalizado')
    # ### end Alembic commands ###
