"""Baseline inicial

Revision ID: 48e0342aacb1
Revises: 6f234e8367a6
Create Date: 2024-12-26 15:34:53.868432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e0342aacb1'
down_revision: Union[str, None] = '6f234e8367a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jogadores_id', table_name='jogadores')
    op.drop_index('ix_jogadores_nome', table_name='jogadores')
    op.drop_table('jogadores')
    op.drop_index('ix_times_divisao', table_name='times')
    op.drop_index('ix_times_id', table_name='times')
    op.drop_index('ix_times_nome', table_name='times')
    op.drop_table('times')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('times',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=True),
    sa.Column('divisao', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_times_nome', 'times', ['nome'], unique=False)
    op.create_index('ix_times_id', 'times', ['id'], unique=False)
    op.create_index('ix_times_divisao', 'times', ['divisao'], unique=False)
    op.create_table('jogadores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('idade', sa.INTEGER(), nullable=False),
    sa.Column('posicao', sa.VARCHAR(), nullable=False),
    sa.Column('naturalidade', sa.VARCHAR(), nullable=False),
    sa.Column('id_time', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_time'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jogadores_nome', 'jogadores', ['nome'], unique=False)
    op.create_index('ix_jogadores_id', 'jogadores', ['id'], unique=False)
    # ### end Alembic commands ###
