"""Adicionando tabela Gols

Revision ID: 9e9569504531
Revises: b610326f4661
Create Date: 2024-12-30 09:33:46.607243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9569504531'
down_revision: Union[str, None] = 'b610326f4661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gols_jogo',
    sa.Column('jogo_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ),
    sa.PrimaryKeyConstraint('jogo_id', 'jogador_id')
    )
    op.add_column('jogadores', sa.Column('gols_realizados', sa.Integer(), nullable=True))
    op.add_column('times', sa.Column('gols_feitos', sa.Integer(), nullable=True))
    op.add_column('times', sa.Column('gols_sofridos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('times', 'gols_sofridos')
    op.drop_column('times', 'gols_feitos')
    op.drop_column('jogadores', 'gols_realizados')
    op.drop_table('gols_jogo')
    # ### end Alembic commands ###
