"""Corrige inconsistências de índices

Revision ID: a18310fe4f32
Revises: 
Create Date: 2025-03-17 13:45:53.524244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18310fe4f32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sigla', sa.String(length=4), nullable=True),
    sa.Column('divisao', sa.String(), nullable=True),
    sa.Column('gols_feitos', sa.Integer(), nullable=True),
    sa.Column('gols_sofridos', sa.Integer(), nullable=True),
    sa.Column('vitorias', sa.Integer(), nullable=True),
    sa.Column('derrotas', sa.Integer(), nullable=True),
    sa.Column('empates', sa.Integer(), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_times_divisao'), 'times', ['divisao'], unique=False)
    op.create_index(op.f('ix_times_id'), 'times', ['id'], unique=False)
    op.create_index(op.f('ix_times_nome'), 'times', ['nome'], unique=False)
    op.create_table('jogadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.String(), nullable=False),
    sa.Column('id_time', sa.Integer(), nullable=True),
    sa.Column('gols_realizados', sa.Integer(), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.Column('cartoes_amarelos', sa.Integer(), nullable=True),
    sa.Column('cartoes_vermelhos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_time'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jogadores_id'), 'jogadores', ['id'], unique=False)
    op.create_index(op.f('ix_jogadores_nome'), 'jogadores', ['nome'], unique=False)
    op.create_table('jogos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_casa_id', sa.Integer(), nullable=True),
    sa.Column('time_visitante_id', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('placar_casa', sa.Integer(), nullable=True),
    sa.Column('placar_visitante', sa.Integer(), nullable=True),
    sa.Column('time_ganhador', sa.Integer(), nullable=True),
    sa.Column('time_derrotado', sa.Integer(), nullable=True),
    sa.Column('jogo_finalizado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['time_casa_id'], ['times.id'], ),
    sa.ForeignKeyConstraint(['time_derrotado'], ['times.id'], ),
    sa.ForeignKeyConstraint(['time_ganhador'], ['times.id'], ),
    sa.ForeignKeyConstraint(['time_visitante_id'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jogos_id'), 'jogos', ['id'], unique=False)
    op.create_table('gols_jogo',
    sa.Column('jogo_id', sa.Integer(), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogos.id'], ),
    sa.PrimaryKeyConstraint('jogo_id', 'jogador_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gols_jogo')
    op.drop_index(op.f('ix_jogos_id'), table_name='jogos')
    op.drop_table('jogos')
    op.drop_index(op.f('ix_jogadores_nome'), table_name='jogadores')
    op.drop_index(op.f('ix_jogadores_id'), table_name='jogadores')
    op.drop_table('jogadores')
    op.drop_index(op.f('ix_times_nome'), table_name='times')
    op.drop_index(op.f('ix_times_id'), table_name='times')
    op.drop_index(op.f('ix_times_divisao'), table_name='times')
    op.drop_table('times')
    # ### end Alembic commands ###
