"""Corrige colunas duplicadas

Revision ID: ab5632d7828b
Revises: 3425a8bbbcec
Create Date: 2025-02-19 11:03:48.893311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5632d7828b'
down_revision: Union[str, None] = '3425a8bbbcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    with op.batch_alter_table("times") as batch_op:
        batch_op.add_column(sa.Column("vitorias", sa.Integer(), nullable=True, server_default="0"))
        batch_op.add_column(sa.Column("derrotas", sa.Integer(), nullable=True, server_default="0"))
        batch_op.add_column(sa.Column("empates", sa.Integer(), nullable=True, server_default="0"))
        batch_op.add_column(sa.Column("pontuacao", sa.Integer(), nullable=True, server_default="0"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('times', 'pontuacao')
    op.drop_column('times', 'empates')
    op.drop_column('times', 'derrotas')
    op.drop_column('times', 'vitorias')
    op.drop_constraint(None, 'jogos', type_='foreignkey')
    op.drop_constraint(None, 'jogos', type_='foreignkey')
    # ### end Alembic commands ###
