"""Adicionando tabela Jogos

Revision ID: b610326f4661
Revises: b59adf35a3f8
Create Date: 2024-12-30 08:54:45.629401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b610326f4661'
down_revision: Union[str, None] = 'b59adf35a3f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_casa_id', sa.Integer(), nullable=True),
    sa.Column('time_visitante_id', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('placar_casa', sa.Integer(), nullable=True),
    sa.Column('placar_visitante', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['time_casa_id'], ['times.id'], ),
    sa.ForeignKeyConstraint(['time_visitante_id'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jogos_id'), 'jogos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jogos_id'), table_name='jogos')
    op.drop_table('jogos')
    # ### end Alembic commands ###
