"""Removendo campo naturalidade

Revision ID: c7311826e7d5
Revises: 48e0342aacb1
Create Date: 2024-12-27 08:39:19.334507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7311826e7d5'
down_revision: Union[str, None] = '48e0342aacb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('divisao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_times_divisao'), 'times', ['divisao'], unique=False)
    op.create_index(op.f('ix_times_id'), 'times', ['id'], unique=False)
    op.create_index(op.f('ix_times_nome'), 'times', ['nome'], unique=False)
    op.create_table('jogadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.String(), nullable=False),
    sa.Column('id_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_time'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jogadores_id'), 'jogadores', ['id'], unique=False)
    op.create_index(op.f('ix_jogadores_nome'), 'jogadores', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jogadores_nome'), table_name='jogadores')
    op.drop_index(op.f('ix_jogadores_id'), table_name='jogadores')
    op.drop_table('jogadores')
    op.drop_index(op.f('ix_times_nome'), table_name='times')
    op.drop_index(op.f('ix_times_id'), table_name='times')
    op.drop_index(op.f('ix_times_divisao'), table_name='times')
    op.drop_table('times')
    # ### end Alembic commands ###
