"""Adiciona campo sigla na tabela times

Revision ID: d6ca3bfc7509
Revises: ab5632d7828b
Create Date: 2025-03-06 09:22:16.733478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ca3bfc7509'
down_revision: Union[str, None] = 'ab5632d7828b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("jogos") as batch_op:
        batch_op.create_foreign_key("fk_jogos_time_ganhador", "times", ["time_ganhador"], ["id"])
        batch_op.create_foreign_key("fk_jogos_time_derrotado", "times", ["time_derrotado"], ["id"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'times', type_='unique')
    op.drop_constraint(None, 'jogos', type_='foreignkey')
    op.drop_constraint(None, 'jogos', type_='foreignkey')
    # ### end Alembic commands ###
